language: node_js
node_js:
  - 4
script: cd frontend && npm install && npm run travis
before_install:
	services:
	- xvfb
    - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
    - npm -v
branches:
  only:
    - master
